name: Build runner image and update cloud run worker pool

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build.yaml'
      - 'Dockerfile'
      - 'create_jwt_token.sh'
      - 'start.sh'

permissions:
  contents: read
  id-token: write

jobs:
  build-push-and-update-runner-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - id: auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v3
        with:
          project_id: nav-data-management-dev
          credentials_json: '${{ secrets.SERVICE_ACCOUNT_CREDS }}'

      - run: echo "TAG=$(git log -1 --pretty=%ad --date=format:%Y%m%d-%H%M%S)" >> $GITHUB_ENV

      - uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            europe-west1-docker.pkg.dev/nav-data-management-dev/images/union-ci-runner:${{ env.TAG }}
