name: Build runner image and update cloud run worker pool

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build.yaml'
      - 'Dockerfile'
      - 'create_jwt_token.sh'
      - 'start.sh'

env:
  CLOUD_RUN_DEV_PROJECT: nav-data-union-ci-dev
  CLOUD_RUN_WORKER_POOL_NAME: union-ci-worker-pool

permissions:
  contents: read
  id-token: write

jobs:
  build-push-and-update-runner-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - id: auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v3
        with:
          token_format: access_token
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.CI_SERVICE_ACCOUNT_EMAIL }}

      - uses: docker/login-action@v3
        name: Login to Google Artifact Registry
        with:
          registry: europe-west1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - run: echo "TAG=$(git log -1 --pretty=%ad --date=format:%Y%m%d-%H%M%S)" >> $GITHUB_ENV

      - uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            europe-west1-docker.pkg.dev/nav-data-management-dev/images/union-ci-runner:${{ env.TAG }}

      - name: Update cloud run worker pool image
        run: |
          gcloud run worker-pools update ${{ env.CLOUD_RUN_WORKER_POOL_NAME }} \
            --project=${{ env.CLOUD_RUN_DEV_PROJECT }} \
            --region=europe-west1 \
            --image=europe-west1-docker.pkg.dev/nav-data-management-dev/images/union-ci-runner:${{ env.TAG }}
